//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fujitsu.AFC.Tasks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fujitsu.AFC.Tasks.Resources.TaskResources", typeof(TaskResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} CaseID {1} CaseTitle {2}.
        /// </summary>
        public static string Audit_AllocateCase {
            get {
                return ResourceManager.GetString("Audit_AllocateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Site {1}.
        /// </summary>
        public static string Audit_AllocatePin {
            get {
                return ResourceManager.GetString("Audit_AllocatePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Case ID {1} Case {2}.
        /// </summary>
        public static string Audit_ArchiveCase {
            get {
                return ResourceManager.GetString("Audit_ArchiveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Root Site Created.
        /// </summary>
        public static string Audit_CaseSiteProvisioning_RootSiteCreated {
            get {
                return ResourceManager.GetString("Audit_CaseSiteProvisioning_RootSiteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Site Created.
        /// </summary>
        public static string Audit_CaseSiteProvisioning_SubSiteCreated {
            get {
                return ResourceManager.GetString("Audit_CaseSiteProvisioning_SubSiteCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Current Project ID {1} New Project ID {2}.
        /// </summary>
        public static string Audit_ChangePrimaryProject {
            get {
                return ResourceManager.GetString("Audit_ChangePrimaryProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Case ID {1} Case {2} .
        /// </summary>
        public static string Audit_CloseCase {
            get {
                return ResourceManager.GetString("Audit_CloseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Case ID {1} Case {2}.
        /// </summary>
        public static string Audit_DeleteCase {
            get {
                return ResourceManager.GetString("Audit_DeleteCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Site {0} Deleted.
        /// </summary>
        public static string Audit_DeletePin {
            get {
                return ResourceManager.GetString("Audit_DeletePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From PIN {0} To PIN {1}.
        /// </summary>
        public static string Audit_MergePin {
            get {
                return ResourceManager.GetString("Audit_MergePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} CaseID {1} CurrentProjectID {2} NewProjectID {3}.
        /// </summary>
        public static string Audit_MoveCase {
            get {
                return ResourceManager.GetString("Audit_MoveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0}.
        /// </summary>
        public static string Audit_RemoveRestrictedUser {
            get {
                return ResourceManager.GetString("Audit_RemoveRestrictedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0}.
        /// </summary>
        public static string Audit_RestrictUser {
            get {
                return ResourceManager.GetString("Audit_RestrictUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Case ID {1} Case Title updated from {2} to Case Title {3}.
        /// </summary>
        public static string Audit_UpdateCaseTitle {
            get {
                return ResourceManager.GetString("Audit_UpdateCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectID {0} PIN{1} Case ID {2} Case Title updated from {3} to CaseTitle {4}.
        /// </summary>
        public static string Audit_UpdateCaseTitleByProject {
            get {
                return ResourceManager.GetString("Audit_UpdateCaseTitleByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Case ID {0} Dictionary Values Updated.
        /// </summary>
        public static string Audit_UpdateCaseWithDictionaryValues {
            get {
                return ResourceManager.GetString("Audit_UpdateCaseWithDictionaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Dictionary Values Updated..
        /// </summary>
        public static string Audit_UpdatePinWithDictionaryValues {
            get {
                return ResourceManager.GetString("Audit_UpdatePinWithDictionaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN {0} Service User Title updated from {1} to Service User Title {2}.
        /// </summary>
        public static string Audit_UpdateServiceUserTitle {
            get {
                return ResourceManager.GetString("Audit_UpdateServiceUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file setting &apos;ReportWindowStartTime&apos; is not valid. Use 24hr clock format e.g. 16:30:00..
        /// </summary>
        public static string ConfigurationFile_InvalidRunTime {
            get {
                return ResourceManager.GetString("ConfigurationFile_InvalidRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file setting [{0}] has not been supplied or is invalid..
        /// </summary>
        public static string ConfigurationFile_SettingMissing {
            get {
                return ResourceManager.GetString("ConfigurationFile_SettingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] A Project does not exist for specified ProjectID [{1}].
        /// </summary>
        public static string OperationsTaskRequest_CaseDoesNotExistForSpecifiedProjectId {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_CaseDoesNotExistForSpecifiedProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] No Project exists on PIN [{1}] for ProjectID [{2}].
        /// </summary>
        public static string OperationsTaskRequest_CaseDoesNotExistForTheSpecifiedProjectIdOnThePin {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_CaseDoesNotExistForTheSpecifiedProjectIdOnThePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] CaseID [{2}] already exists..
        /// </summary>
        public static string OperationsTaskRequest_CaseIdAlreadyExists {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_CaseIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] CaseID [{2}] does not exist..
        /// </summary>
        public static string OperationsTaskRequest_CaseIdDoesNotExist {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_CaseIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] Current ProjectID [{1}] is not assigned to the specified CaseID [{2}]..
        /// </summary>
        public static string OperationsTaskRequest_CurrentProjectIsNotAssignedToTheCase {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_CurrentProjectIsNotAssignedToTheCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] Invalid Dictionary XML..
        /// </summary>
        public static string OperationsTaskRequest_InvalidDictionaryXML {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidDictionaryXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] ProjectID [{1}] Invalid Dictionary XML..
        /// </summary>
        public static string OperationsTaskRequest_InvalidDictionaryXMLWithoutPin {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidDictionaryXMLWithoutPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request Task Name [{0}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestInvalidTaskName {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestInvalidTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No CaseID specified on Task [{0}] for PIN [{1}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoCaseId {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoCaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No CaseTitle specified on Task [{0}] for PIN [{1}] CaseID [{2}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoCaseTitle {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No Current ProjectID specified on Task [{0}] for PIN [{1}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoCurrentProjectId {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoCurrentProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - Task [{0}] No Dictionary has been specified.
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoDictionaryXML {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoDictionaryXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No IsPrimary specified on Task [{0}] for PIN [{1}] CaseID [{2}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoIsPrimary {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoIsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No New ProjectID specified on Task [{0}] for PIN [{1}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoNewProjectId {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoNewProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No PIN value specified on Task [{0}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoPin {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No ProjectID specified on Task [{0}] for PIN [{1}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoProjectId {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No ProjectID specified on Task [{0}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoProjectIdWithoutPin {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoProjectIdWithoutPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No ProjectName specified on Task [{0}] ProjectID [{1}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoProjectName {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Invalid Request - No Site Title specified on Task [{0}] for PIN [{1}].
        /// </summary>
        public static string OperationsTaskRequest_InvalidRequestNoSiteTitle {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_InvalidRequestNoSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] MergePIN request pending..
        /// </summary>
        public static string OperationsTaskRequest_MergePinRequestPending {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_MergePinRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN  [{1}] No Unallocated Sites Available..
        /// </summary>
        public static string OperationsTaskRequest_NoUnallocatedSitesAvailable {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_NoUnallocatedSitesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] already exists..
        /// </summary>
        public static string OperationsTaskRequest_PinAlreadyExists {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_PinAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] does not exist..
        /// </summary>
        public static string OperationsTaskRequest_PinDoesNotExist {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_PinDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] does not exist for the specified CaseID [{2}].
        /// </summary>
        public static string OperationsTaskRequest_PinDoesNotExistForTheSpecifiedCase {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_PinDoesNotExistForTheSpecifiedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - Task [{0}] PIN [{1}] request pending..
        /// </summary>
        public static string OperationsTaskRequest_PinRequestPending {
            get {
                return ResourceManager.GetString("OperationsTaskRequest_PinRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvisioningTaskRequest - Invalid Request Task Name [{0}].
        /// </summary>
        public static string ProvisioningTaskRequest_InvalidRequestInvalidTaskName {
            get {
                return ResourceManager.GetString("ProvisioningTaskRequest_InvalidRequestInvalidTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportTaskRequest - Invalid Request Task Name [{0}].
        /// </summary>
        public static string SupportTaskRequest_InvalidRequestInvalidTaskName {
            get {
                return ResourceManager.GetString("SupportTaskRequest_InvalidRequestInvalidTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}TaskRequest - An unexpected error has occurred please check the Application Event Log for further details..
        /// </summary>
        public static string UnexpectedApplicationError {
            get {
                return ResourceManager.GetString("UnexpectedApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTaskRequest - An unexpected error has occurred please check the Application Event Log using HandlingInstanceId [{0}] for further details..
        /// </summary>
        public static string UnexpectedApplicationErrorInstanceHandlingId {
            get {
                return ResourceManager.GetString("UnexpectedApplicationErrorInstanceHandlingId", resourceCulture);
            }
        }
    }
}
