// <auto-generated />
namespace Fujitsu.AFC.Data.Migrations.AFC
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsClosedColumnAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsClosedColumnAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201605041343145_IsClosedColumnAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
