// <auto-generated />
namespace Fujitsu.AFC.Data.Migrations.AFC
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LibraryCaseIdAndSitePinColumnUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LibraryCaseIdAndSitePinColumnUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "201604251305549_LibraryCaseIdAndSitePinColumnUnique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
