//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fujitsu.AFC.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fujitsu.AFC.Data.DatabaseResources", typeof(DatabaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_AllocateCase                                                           */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_AllocateCase {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_AllocateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_AllocatePIN                                                            */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 22/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_AllocatePIN {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_AllocatePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_ArchiveCase                                                            */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 03/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_ArchiveCase {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_ArchiveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_CaseUrl                                                                */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 05/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_CaseUrl {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_CaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_ChangePrimaryProject                                                   */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 05/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_ChangePrimaryProject {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_ChangePrimaryProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_CloseCase                                                              */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 03/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_CloseCase {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_CloseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_DeletePIN                                                              */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 30/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_DeletePIN {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_DeletePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_GetDictionaryXml                                                    */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 29/03/2016                                                                        */
        ////*                                                                                                */
        ////* Descri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_GetDictionaryXml {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_GetDictionaryXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U       /* ============================================================================================== */
        ///        /* Name:        sp_eAspire_MergePIN                                                               */
        ///        /* Author:		Ray Banister                                                                      */
        ///        /* Create date: 11/04/2016                                                                        */
        ///        /*                                                                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_MergePIN {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_MergePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_MoveCase                                                               */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 05/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_MoveCase {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_MoveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_PINUrl                                                                 */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 29/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_PINUrl {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_PINUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_RemoveRestrictedUser                                                   */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 05/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_RemoveRestrictedUser {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_RemoveRestrictedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_RestrictUser                                                              */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 05/05/2016                                                                        */
        ////*                                                                                                */
        ////*  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_RestrictUser {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_RestrictUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_UpdateCaseTitle                                                        */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 22/04/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_UpdateCaseTitle {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_UpdateCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_UpdateCaseTitleByProject                                               */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 14/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_UpdateCaseTitleByProject {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_UpdateCaseTitleByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_UpdateCaseWithDictionaryValues                                         */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 05/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_UpdateCaseWithDictionaryValues {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_UpdateCaseWithDictionaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_UpdatePINTitle                                                         */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_UpdatePINTitle {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_UpdatePINTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_eAspire_UpdatePINWithDictionaryValues                                          */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 05/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_eAspire_UpdatePINWithDictionaryValues {
            get {
                return ResourceManager.GetString("Create_sp_eAspire_UpdatePINWithDictionaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidateAvailableSites                                                     */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Descrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidateAvailableSites {
            get {
                return ResourceManager.GetString("Create_sp_ValidateAvailableSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidateCaseIdInUse                                                            */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidateCaseIdInUse {
            get {
                return ResourceManager.GetString("Create_sp_ValidateCaseIdInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidateCaseIdRequested                                                        */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 21/04/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidateCaseIdRequested {
            get {
                return ResourceManager.GetString("Create_sp_ValidateCaseIdRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidateDictionary                                                             */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidateDictionary {
            get {
                return ResourceManager.GetString("Create_sp_ValidateDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidateIsPIN_MergeFromPIN                                                     */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidateIsPIN_MergeFromPIN {
            get {
                return ResourceManager.GetString("Create_sp_ValidateIsPIN_MergeFromPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidateIsPIN_MergeToPIN                                                       */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidateIsPIN_MergeToPIN {
            get {
                return ResourceManager.GetString("Create_sp_ValidateIsPIN_MergeToPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidateIsPIN_AwaitingDeletion                                                 */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 17/08/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidateIsPINAwaitingDeletion {
            get {
                return ResourceManager.GetString("Create_sp_ValidateIsPINAwaitingDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidatePIN_ProjectId_Exist                                                    */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 12/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidatePIN_ProjectId_Exists {
            get {
                return ResourceManager.GetString("Create_sp_ValidatePIN_ProjectId_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidatePINExists                                                              */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidatePINExists {
            get {
                return ResourceManager.GetString("Create_sp_ValidatePINExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        sp_ValidatePINRequested                                                           */
        ////* Author:		Ray Banister                                                                      */
        ////* Create date: 23/03/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_ValidatePINRequested {
            get {
                return ResourceManager.GetString("Create_sp_ValidatePINRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        vw_eAspireCase                                                                    */
        ////* Author:		Jonathan King                                                                     */
        ////* Create date: 03/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_vw_eAspireCase {
            get {
                return ResourceManager.GetString("Create_vw_eAspireCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ============================================================================================== */
        ////* Name:        vw_eAspireCase                                                                    */
        ////* Author:		Jonathan King                                                                     */
        ////* Create date: 03/05/2016                                                                        */
        ////*                                                                                                */
        ////* Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_vw_eAspirePIN {
            get {
                return ResourceManager.GetString("Create_vw_eAspirePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_AllocateCase]    Script Date: 03/23/2016 16:57:33 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_AllocateCase]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_AllocateCase]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_AllocateCase {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_AllocateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_AllocatePIN]    Script Date: 03/23/2016 10:19:19 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_AllocatePIN]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_AllocatePIN]
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_AllocatePIN {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_AllocatePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_ArchiveCase]    Script Date: 05/03/2016 08:13:11 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_ArchiveCase]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_ArchiveCase]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_ArchiveCase {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_ArchiveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_CaseUrl]    Script Date: 05/05/2016 17:17:17 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_CaseUrl]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_CaseUrl]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_CaseUrl {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_CaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_ChangePrimaryProject]    Script Date: 05/05/2016 14:23:37 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_ChangePrimaryProject]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_ChangePrimaryProject]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_ChangePrimaryProject {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_ChangePrimaryProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_CloseCase]    Script Date: 05/03/2016 11:48:15 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_CloseCase]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_CloseCase]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_CloseCase {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_CloseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_DeletePIN]    Script Date: 03/30/2016 08:39:13 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_DeletePIN]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_DeletePIN]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_DeletePIN {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_DeletePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_GetDictionaryXml]    Script Date: 04/11/2016 08:34:09 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_GetDictionaryXml]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_GetDictionaryXml]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_GetDictionaryXml {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_GetDictionaryXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_MergePIN]    Script Date: 04/11/2016 16:07:07 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_MergePIN]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_MergePIN]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_MergePIN {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_MergePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_MoveCase]    Script Date: 05/05/2016 15:28:56 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_MoveCase]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_MoveCase]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_MoveCase {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_MoveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_PINUrl]    Script Date: 03/29/2016 13:51:40 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_PINUrl]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_PINUrl]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_PINUrl {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_PINUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_RemoveRestrictedUser]    Script Date: 05/05/2016 15:44:04 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_RemoveRestrictedUser]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_RemoveRestrictedUser]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_RemoveRestrictedUser {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_RemoveRestrictedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_RestrictUser]    Script Date: 05/05/2016 15:44:31 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_RestrictUser]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_RestrictUser]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_RestrictUser {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_RestrictUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_UpdateCaseTitle]    Script Date: 04/22/2016 13:34:35 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_UpdateCaseTitle]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_UpdateCaseTitle]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_UpdateCaseTitle {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_UpdateCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_UpdateCaseTitleByProject]    Script Date: 04/12/2016 07:54:59 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_UpdateCaseTitleByProject]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_UpdateCaseTitleByProject]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_UpdateCaseTitleByProject {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_UpdateCaseTitleByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_UpdateCaseWithDictionaryValues]    Script Date: 05/05/2016 18:14:19 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_UpdateCaseWithDictionaryValues]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_UpdateCaseWithDictionaryValues]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_UpdateCaseWithDictionaryValues {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_UpdateCaseWithDictionaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_UpdatePINTitle]    Script Date: 03/23/2016 14:01:08 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_UpdatePINTitle]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_UpdatePINTitle]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_UpdatePINTitle {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_UpdatePINTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_eAspire_UpdatePINWithDictionaryValues]    Script Date: 05/05/2016 17:32:30 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_eAspire_UpdatePINWithDictionaryValues]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_eAspire_UpdatePINWithDictionaryValues]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_eAspire_UpdatePINWithDictionaryValues {
            get {
                return ResourceManager.GetString("Drop_sp_eAspire_UpdatePINWithDictionaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidateAvailableSites]    Script Date: 03/23/2016 10:19:54 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidateAvailableSites]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidateAvailableSites]
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidateAvailableSites {
            get {
                return ResourceManager.GetString("Drop_sp_ValidateAvailableSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidateCaseIdInUse]    Script Date: 03/23/2016 16:53:40 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidateCaseIdInUse]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidateCaseIdInUse]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidateCaseIdInUse {
            get {
                return ResourceManager.GetString("Drop_sp_ValidateCaseIdInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidateCaseIdRequested]    Script Date: 05/06/2016 13:39:00 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidateCaseIdRequested]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidateCaseIdRequested]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidateCaseIdRequested {
            get {
                return ResourceManager.GetString("Drop_sp_ValidateCaseIdRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidateDictionary]    Script Date: 03/23/2016 10:20:51 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidateDictionary]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidateDictionary]
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidateDictionary {
            get {
                return ResourceManager.GetString("Drop_sp_ValidateDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidateIsPIN_MergeFromPIN]    Script Date: 03/23/2016 16:40:24 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidateIsPIN_MergeFromPIN]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidateIsPIN_MergeFromPIN]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidateIsPIN_MergeFromPIN {
            get {
                return ResourceManager.GetString("Drop_sp_ValidateIsPIN_MergeFromPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidateIsPIN_MergeToPIN]    Script Date: 03/30/2016 07:52:51 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidateIsPIN_MergeToPIN]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidateIsPIN_MergeToPIN]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidateIsPIN_MergeToPIN {
            get {
                return ResourceManager.GetString("Drop_sp_ValidateIsPIN_MergeToPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidateIsPIN_AwaitingDeletion]    Script Date: 08/23/2016 15:18:26 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidateIsPIN_AwaitingDeletion]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidateIsPIN_AwaitingDeletion]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidateIsPINAwaitingDeletion {
            get {
                return ResourceManager.GetString("Drop_sp_ValidateIsPINAwaitingDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [AFC.DCF.Database]
        ///GO
        ///
        ////****** Object:  StoredProcedure [dbo].[sp_ValidatePIN_ProjectId_Exists]    Script Date: 05/12/2016 16:56:40 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidatePIN_ProjectId_Exists]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidatePIN_ProjectId_Exists]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidatePIN_ProjectId_Exists {
            get {
                return ResourceManager.GetString("Drop_sp_ValidatePIN_ProjectId_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidatePINExists]    Script Date: 03/23/2016 10:22:08 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidatePINExists]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidatePINExists]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidatePINExists {
            get {
                return ResourceManager.GetString("Drop_sp_ValidatePINExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  StoredProcedure [dbo].[sp_ValidatePINRequested]    Script Date: 03/30/2016 09:26:38 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[sp_ValidatePINRequested]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [dbo].[sp_ValidatePINRequested]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_sp_ValidatePINRequested {
            get {
                return ResourceManager.GetString("Drop_sp_ValidatePINRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[vw_eAspireCase]    Script Date: 05/06/2016 07:41:00 ******/
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[dbo].[vw_eAspireCase]&apos;))
        ///DROP VIEW [dbo].[vw_eAspireCase]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_vw_eAspireCase {
            get {
                return ResourceManager.GetString("Drop_vw_eAspireCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  View [dbo].[vw_eAspirePIN]    Script Date: 05/06/2016 07:44:33 ******/
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[dbo].[vw_eAspirePIN]&apos;))
        ///DROP VIEW [dbo].[vw_eAspirePIN]
        ///GO
        ///
        ///.
        /// </summary>
        internal static string Drop_vw_eAspirePIN {
            get {
                return ResourceManager.GetString("Drop_vw_eAspirePIN", resourceCulture);
            }
        }
    }
}
